# Defines the internal name of your Spring Boot application
spring.application.name=type-safe-config

# --- Cloud Storage Settings ---

# The unique identifier for your cloud service authentication
cloud.storage.api-key=XW-9988-ABC

# Secret credential used to sign requests for security
cloud.storage.secret-key=super-secret-123

# The specific folder or container name where files will be stored
cloud.storage.bucket-name=xworkz-backups

# Maximum time (in seconds) the application will wait for a response before failing
cloud.storage.timeout-seconds=30